### ISSUE TITLE
npm dependency causes install failure

### ISSUE THREAD

**Issue by davepinkawa** [ArkEcosystem/ark-deployer#11]
> npm WARN optional Skipping failed optional dependency /angular-cli/chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
> npm WARN optional Skipping failed optional dependency /forever/chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
> npm WARN @angular/core@2.4.10 requires a peer of rxjs@^5.0.1 but none was installed.
> npm ERR! Linux 4.13.0-1007-azure
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "forever" "grunt-cli" "node-sass" "angular-cli"
> npm ERR! node v4.2.6
> npm ERR! npm  v3.5.2
> npm ERR! path /usr/local/lib
> npm ERR! code EACCES
> npm ERR! errno -13
> npm ERR! syscall access
> 
> npm ERR! Error: EACCES: permission denied, access '/usr/local/lib'
> npm ERR!     at Error (native)
> npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib']
> npm ERR!   errno: -13,
> npm ERR!   code: 'EACCES',
> npm ERR!   syscall: 'access',
> npm ERR!   path: '/usr/local/lib' }
> npm ERR!
> npm ERR! Please try running this command again as root/Administrator.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/arkadmin/npm-debug.log
> ==> Stopping...

Trying to get a single script to handle installation into an Ubuntu 16.04LTS VM. Running into this issue right now on a clean VM where the only packages installed before running ./sidechain install-node are:  npm, jq. Both of these packages require sudo privileges to install from my testing.

Attempting to install npm without sudo results in "Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)" not sure if that is behavior others experience with fresh 16.04LTS machines?

**Comment by alexbarnsley** [comment]
@davepinkawa have you taken a look at `https://github.com/ArkEcosystem/ark-deployer/blob/master/vagrant/setup.sh`? This is run on a vagrant setup for Ubuntu 16.04 (xenial) and does everything itself, so will likely work for you too. Please close the issue if this helps.

**Comment by davepinkawa** [comment]
Unfortunately I'm attempting to run this in Azure as a Quick Deploy option, so Vagrant isn't an option since nested virtualization is only available in the most expensive tier of VMs (Not great for an affordable short-term demonstration deployment).

I think the issue is that the script initially is referencing:
npm WARN checkPermissions Missing write access to /usr/local/lib
/usr/local/lib
├─┬ angular-cli@1.0.0-beta.28.3
│ ├─┬ @angular-cli/ast-tools@1.0.16
│ │ ├─┬ @angular/tsc-wrapped@0.5.2
│ │ │ └─┬ tsickle@0.2.6
│ │ │   └── source-map-support@0.4.18
│ │ ├── denodeify@1.2.1
│ │ ├─┬ **rxjs@5.1.0**

But when it complains about unmet peer dependency, it's referencing:
 ├── UNMET PEER DEPENDENCY **rxjs@^5.0.1**

I'm not sure if this is a typo or just a small mix-up, but I'm also not familiar enough to go in and try and fix this myself. Looks like 5.1.0 vs 5.0.1 might have just been a small typo?

Unfortunately Azure VMs with nested virtualization enabled are in the $1000-$3,000 dollar per month range, so this isn't ideal for a quick test sidechain...

**Comment by alexbarnsley** [comment]
Yeh, I understand you're not using vagrant and not suggesting it in this case. I linked to the script as it's used to deploy both node and explorer on a vagrant ubuntu environment. It can be tweaked to run on a stand-alone ubuntu setup.

I don't think it's a typo but I think it's specific to your environment in Azure as I've never come across this issue up to this point. Do you have any sort of script to had that I can see?

**Comment by davepinkawa** [comment]
I'll take a closer look at the vagrant setup if it can install the node and explorer locally instead of spinning up a new vagrant box. I've only ever used vagrant with Hyper-V deployment options for new VMs, never with setting up a local environment if that's possible...

I actually hadn't scripted any portion of the process while running into the originating error above. Solely created a new Ubuntu 16.04-LTS VM, and then ran in subsequent order the 'installation' section and the 'Node' section of the Readme file. 

I can create a new blank VM from scratch and provide access if you prefer first-hand understanding of that.

**Comment by alexbarnsley** [comment]
I had issues with Docker, but i'd never used it before so probably the reason. If you want to spin up an Azure setup, I can see if I can get a sidechain running on it for you? Then we can document that process

**Comment by alexbarnsley** [comment]
@davepinkawa I was able to get it working with Azure just following the normal steps. I believe you was as well, am I right? If so, can you close this issue please 👍
