### ISSUE TITLE
Runaway forever logs

### ISSUE THREAD

**Issue by vRobM** [ArkEcosystem/ark-deployer#20]
Hiya,
Have a bridgechain running for a month and noticed the ~/.forever/xxxx.log growing into the GBs.

Is there a way to set up log rotation and a reasonable size target size?

The logs seem to log a lot of debug which may not be needed for a long running bridge chain.
How can we adjust that?

Let's say you fix the log rotation, what is the proper way to upgrade the code already running?

This brings up lots of questions as to how to best run bridgechains longterm.

**Comment by alexbarnsley** [comment]
Closing in favour of #29
