### ISSUE TITLE
Incorrectly named database?

### ISSUE THREAD

**Issue by Guppster** [ArkEcosystem/ark-deployer#23]
Following the steps at https://github.com/ArkEcosystem/ark-deployer#vagrant
I am unable to connect to the API. The explorer is running but has no information. 
 
**Tried starting node manually**
`node app.js -p 14100 -a 127.0.0.1 ./config.MyTest.autoforging.json -g genesisBlock.MyTest.json`
```
[log] 2018-03-31 21:50:03 | error - error: FATAL:  database "ark_test" does not exist
[log] 2018-03-31 21:50:03 | error - connection: {"host":"localhost","port":5432,"database":"ark_test","user":"vagrant","password":"########","poolSize":2
0,"poolIdleTimeout":30000,"reapIntervalMillis":1000,"logEvents":["error"]}
[FTL] 2018-03-31 21:50:03 | Error: FATAL:  database "ark_test" does not exist
```

**Checked which databases exist**
`psql -lqt | cut -d \| -f 1`

```
ark_mytest
postgres
template0
template1
```
app.js is looking for ark_test but the database is named ark_mytest.
So it appears the database is created with the wrong name? or the node starts with the wrong config. 
config.MyTest.json does have `"database": "ark_mytest"` but the script is still looking for ark_test

To reproduce 
- Clone
- `vagrant up`
- node.log is empty / explorer has no data

**Comment by Guppster** [comment]
I realized I forgot to specify the --config flag in my attempt to start the node manually above :joy:
so running 
`forever start -s app.js --config config.MyTest.autoforging.json --genesis genesisBlock.MyTest.json`
does fix start the node with the correct database and everything works.

The issue of the node not running after running `vagrant up` still remains though.

**Comment by alexbarnsley** [comment]
I think this is caused by 3 commits that I made yesterday. I've reverted them now and branched them (should have done this in the first place). Could you pull down the changes and try again please?

**Comment by Guppster** [comment]
Yup it works now! Thanks Alex
