### ISSUE TITLE
You need to install postgresql-server-dev-X.Y for building a server-side extension | Ubuntu 16.04

### ISSUE THREAD

**Issue by ChenePoli** [ArkEcosystem/ark-deployer#3]
Got that issue on Ubuntu 16.04 : 
https://zupimages.net/up/18/04/sajf.png
Solved with : 
https://www.postgresql.org/download/linux/ubuntu/  &
sudo apt-get install postgresql
sudo apt-get install python-psycopg2
sudo apt-get install libpq-dev

**Comment by alexbarnsley** [comment]
Interesting. I don't have this issue. Vagrant is using a ubuntu/xenial64 image which is also 16.04. Is there anything special about your server setup?

The deployer installs the dependencies on this line: https://github.com/ArkEcosystem/ark-deployer/blob/master/sidechain.sh#L16 which include postgresql and libpq-dev already. I will spin up a brand new Ubuntu 16.04 virtual machine which isn't vagrant and try that.

Thanks.

**Comment by alexbarnsley** [comment]
@ChenePoli I've installed this quite a few times on different Ubuntu 16 setups and not come across any issues, as well as many other people. The deployer already installs dependencies which are working on many other setups. If you get chance, can you try and install again and if it's still an issue, post the command you used to run also. All output of the bash terminal if possible.

I will close for now as i think this might be a specific scenario to you, but please re-open if you do re-test and let me know. Thanks.
