### ISSUE TITLE
[Enhancement] - Provide chain parameters through config JSON

### ISSUE THREAD

**Issue by nejt** [ArkEcosystem/ark-deployer#4]
Great work - thank you for this functionality! It is an amazing start. 

If I may make a few suggestions for improvements.  
1. I would suggest creating a JSON to pass the initialization parameters of the chain: "initConfig.json"

In ark-node you already use: "networks.json".  I believe it would be more clear if you created a json for this project that supersedes that json.  Then line 51 in "app/app-node.sh" could be a simple: 
`mv "initConfig.json" "$SIDECHAIN_PATH/networks.json"`

2. It would also be nice to set totalpremine on line 69 of "tasks/createGenesisBlock.js".  Again this could be part of the "initConfig.json".

3. You could also increase the scope of the variables a new chain could implement by modifying "helpers/constants.js".  I believe it would be good to allow developers to set the following parameters: 
fees
totalAmount

This would require adding a link to the networks.json...
`var networks = require('../networks.json');`

Hopefully I can get some time and I'll try a fork to test this out.  But I wanted to throw this out there...

Again - great work. It is great to see regular progress on a project!

**Comment by alexbarnsley** [comment]
Thanks for your submission @nejt - I've only just seen it. I have just finished merging some customisation properties for sidechains. I will remember these and may take a look soon, as I do think JSON may be a good alternative.
